export const STATIC_KEYS = [
  "claimBonus",
  "getTheBonus",
  "exclusiveWelcomeOfferOf",
  "logIn",
  "signUp",
  "topCasinos",
  "welcomeBonus",
  "allCasino",
  "bonusDetails",
  "casino",
  "bonuses",
  "rate",
  "freeSpins",
  "moreInfo",
  "get",
  "maximumAmount",
  "wager",
  "refresh",
  "bonusCode",
  "advantages",
  "knowMore",
  "app",
  "topGames",
  "playNow",
  "allGames",
  "paymentMethods",
  "deposit",
  "type",
  "country",
  "commission",
  "processingTime",
  "minimumDeposit",
  "softwareProviders",
  "overview",
] as const;

export type StaticKey = (typeof STATIC_KEYS)[number];

export type StaticDict = Record<StaticKey, string>;
