// AUTO-GENERATED by commands/update-font-only.ts
import localFont from "next/font/local";

export const roboto = localFont({
  src: [
    {
      path: "../../public/fonts/Roboto/Roboto-500.ttf",
      weight: "500",
      style: "normal",
    },
    {
      path: "../../public/fonts/Roboto/Roboto-900.ttf",
      weight: "900",
      style: "normal",
    },
  ],
  variable: "--font-primary",
  display: "swap",
  preload: true,
  adjustFontFallback: false,
});

export const cinzel = localFont({
  src: [
    {
      path: "../../public/fonts/Cinzel/Cinzel-VAR.ttf",
      weight: "100 900",
      style: "normal",
    },
  ],
  variable: "--font-secondary",
  display: "swap",
  preload: true,
  adjustFontFallback: false,
});

export const beVietnamPro = localFont({
  src: [
    {
      path: "../../public/fonts/BeVietnamPro-Black.ttf",
      weight: "100 900",
      style: "normal",
    },
  ],
  variable: "--font-third",
  display: "swap",
  preload: true,
  adjustFontFallback: false,
});
