// AUTO-GENERATED by commands/update-font-only.ts
import localFont from "next/font/local";

export const roboto = localFont({
  src: [
    {
      path: "../../public/fonts/Roboto/Roboto-500.ttf",
      weight: "500",
      style: "normal",
    },
    {
      path: "../../public/fonts/Roboto/Roboto-900.ttf",
      weight: "900",
      style: "normal",
    },
  ],
  variable: "--font-primary",
  display: "swap",
  preload: true,
  adjustFontFallback: false,
});

export const mogra = localFont({
  src: [
    {
      path: "../../public/fonts/Mogra/Mogra-400.ttf",
      weight: "400",
      style: "normal",
    },
  ],
  variable: "--font-secondary",
  display: "swap",
  preload: true,
  adjustFontFallback: false,
});

export const monserrat = localFont({
  src: [
    {
      path: "../../public/fonts/Montserrat-Black.ttf",
      weight: "900",
      style: "normal",
    },
  ],
  variable: "--font-third",
  display: "swap",
  preload: true,
  adjustFontFallback: false,
});
